/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-24 13:08:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.professors.consulting;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.sun.student.model.vo.Student;
import com.sun.student.model.vo.PageInfo;
import com.sun.user.model.vo.User;

public final class professorsConsultingView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/professors/consulting/../../../views/common/menubar.jsp", Long.valueOf(1629808238000L));
    _jspx_dependants.put("/views/professors/consulting/../../../views/common/../common/logoutIndex.jsp", Long.valueOf(1629808238000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sun.student.model.vo.Student");
    _jspx_imports_classes.add("com.sun.student.model.vo.PageInfo");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.sun.user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Student> sList = (ArrayList<Student>)request.getAttribute("sList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	#consulting-table  tfoot,\r\n");
      out.write("	#content-div,\r\n");
      out.write("	h3{\r\n");
      out.write("		text-align:center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	button {\r\n");
      out.write("		border-style: groove;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		background: white;\r\n");
      out.write("		margin: left;\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("	table{\r\n");
      out.write("		font-size:14px;\r\n");
      out.write("		width: max-content ;\r\n");
      out.write("		height: max-content ;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#insert-table input{\r\n");
      out.write("		height:100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#consulting-table{\r\n");
      out.write("		margin-top:50px;\r\n");
      out.write("		margin-left:5%;\r\n");
      out.write("		width:90%;	\r\n");
      out.write("		border: 3px solid #00205b;\r\n");
      out.write("		border-collapse: collapse; \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	header{\r\n");
      out.write("		font-size:14px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div{\r\n");
      out.write("		font-size:14px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#consulting-table  th {\r\n");
      out.write("		border: 1px solid white;\r\n");
      out.write("		background-color: #00205b;\r\n");
      out.write("		color: white;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		padding : 4px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#insert-table td{\r\n");
      out.write("		padding-left : 10px;\r\n");
      out.write("		padding-right : 10px;\r\n");
      out.write("	}\r\n");
      out.write("	#consulting-table  td{\r\n");
      out.write("		border: 1px solid #00205b;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		color: #00205b;\r\n");
      out.write("		padding : 4px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#insert-div{\r\n");
      out.write("		display:inline-block;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#delete-btn,\r\n");
      out.write("	#update-btn{\r\n");
      out.write("		visibility: hidden;\r\n");
      out.write("		display:none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.pagingArea{\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		margin-top:10px;\r\n");
      out.write("	}\r\n");
      out.write("	#footer-div{\r\n");
      out.write("		position:fixed;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		height:150px; \r\n");
      out.write("		bottom: 0;\r\n");
      out.write("    	width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

User loginUser = (User) session.getAttribute("loginUser");
String msg = (String) session.getAttribute("msg");
String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("<!--login이 되어있을 때의 style -->\r\n");
      out.write("\r\n");
      out.write("#top{\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" #logo { \r\n");
      out.write(" 	display:block-inline;\r\n");
      out.write("	padding-right: 80%;\r\n");
      out.write("	text-decoration-line: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-user-name, #logout {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: #00205b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu ul li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #00205b;\r\n");
      out.write("	float: left;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-left: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu .menuLink {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 125px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu .menuLink:hover {\r\n");
      out.write("	color: #092d70;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo:link {text-decoration: none;}\r\n");
      out.write("#logo:visited {text-decoration: none;}\r\n");
      out.write("#logo:hover {text-decoration:  none;}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("	height: 5%;\r\n");
      out.write("}\r\n");
      out.write("nav {\r\n");
      out.write("	background-color: rgb(3, 33, 89);\r\n");
      out.write("	margin: 5px 0px;\r\n");
      out.write("}\r\n");
      out.write("nav>ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	margin-right: 300px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("nav li {\r\n");
      out.write("	float:left;\r\n");
      out.write("	width: 15%;\r\n");
      out.write("	/*margin: 10%;*/\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("/*\r\n");
      out.write("div{\r\n");
      out.write(" border: 1px solid red;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$( function(){\r\n");
      out.write("		var msg=\"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("		if (msg != \"null\") {\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("	function loginVaildate() {\r\n");
      out.write("		if ($(\"#userId\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$(\"#userId\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if ($(\"#userPwd\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			$(\"#userPwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		");

		if (loginUser == null) {
		
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("login이 안 되어있을 때의 style \r\n");
      out.write("-->\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #dae6f0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	padding-right: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#find-div>a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-container {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	background-color: #63718b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-logo, #main-img {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-div {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-left: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-btn {\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	outline: 0;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lock-div {\r\n");
      out.write("	margin-top: 120px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-text {\r\n");
      out.write("	font-size: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lock-img {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	vertical-align: text-bottom;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#find-div {\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	function loginVaildate() {\r\n");
      out.write("		if ($(\"#userId\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$(\"#userId\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if ($(\"#userPwd\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			$(\"#userPwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div id=\"main-div\">\r\n");
      out.write("			<img id=\"main-logo\" src=\"resources/images/sunLogo1.png\" alt=\"\"\r\n");
      out.write("				width=\"200px\"> <img id=\"main-img\"\r\n");
      out.write("				src=\"resources/images/sunUni.jpg\" alt=\"\" width=\"500px\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"main-container\">\r\n");
      out.write("			<div id=\"lock-div\">\r\n");
      out.write("				<img id=\"lock-img\" src=\"resources/images/lock.png\" alt=\"\"\r\n");
      out.write("					width=\"100px\"> <span id=\"login-text\">LOGIN</span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login\"\r\n");
      out.write("				method=\"post\" onsubmit=\"return loginVaildate();\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><label for=\"userId\">아이디</label></th>\r\n");
      out.write("						<td><input type=\"text\" id=\"userId\" name=\"userId\"></td>\r\n");
      out.write("\r\n");
      out.write("						<td rowspan=\"2\"><button type=\"submit\" id=\"login-btn\">LOGIN</button></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><label for=\"userPwd\">비밀번호</label></th>\r\n");
      out.write("						<td><input type=\"password\" id=\"userPwd\" name=\"userPwd\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"find-div\">\r\n");
      out.write("				<a onclick=\"findId();\">>학번/교직원 번호 찾기</a> <a onclick=\"resetPwd();\">>비밀번호\r\n");
      out.write("					초기화 </a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<div id=\"top\" style=\"background-color:white;\">\r\n");
      out.write("			<a id='logo' href=\"");
      out.print(contextPath);
      out.write("\"> <img src=\"resources/images/sunLogo1.png\" width=\"140px\" height=\"70px\"></a> \r\n");
      out.write("			<span id=\"login-user-name\"> ");
      out.print(loginUser.getUserName() );
      out.write("님\r\n");
      out.write("			<a href = \"");
      out.print(contextPath);
      out.write("/logout\">로그아웃</a></span>\r\n");
      out.write("		\r\n");
      out.write("	<nav id=\"topMenu\">\r\n");
      out.write("	");

	if (Character.toUpperCase(loginUser.getUserId().charAt(0)) == 'A') { //관리자
	
      out.write("\r\n");
      out.write("	<div align=\"right\" >\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goStudentManagement();\">학생 관리</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goManageProfessors();\">교수 관리</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goManageClass();\">강의 관리</div></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	} else if (Character.toUpperCase(loginUser.getUserId().charAt(0)) == 'P') { //교수
	
      out.write("\r\n");
      out.write("	<div align=\"right\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goProfessorsClass();\">강의</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goProfessorsGrade();\">성적</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goProfessorsConsulting();\">상담</div></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	} else { // 학생
	
      out.write("\r\n");
      out.write("	<div align=\"left\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goStudentRegister();\">학적</div></li>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goStudentConsulting();\">상담</div></li>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goStudentGrade();\">성적</div></li>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goCertification('https://www.webminwon.com/#reload');\">증명서발급</div></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
}}
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("    \r\n");
      out.write("   function goStudentManagement(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/list.st\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goProfessorsClass(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/classList.pr\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function goProfessorsGrade(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/gradeList.pr\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goProfessorsConsulting(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/consultingList.pr\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goStudentRegister(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/StudentAcademic\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goStudentConsulting(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/student.consult\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goStudentGrade(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/student.grade\";\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goCertification(url) {\r\n");
      out.write("        var win = window.open(url, '_blank');\r\n");
      out.write("        win.focus();\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	function findId(){\r\n");
      out.write("		window.open(\"");
      out.print(contextPath);
      out.write("/findIdForm.us\",\"아이디 찾기\",\"width=500, height=300\");\r\n");
      out.write("	}\r\n");
      out.write("	function resetPwd(){\r\n");
      out.write("		window.open(\"");
      out.print(contextPath);
      out.write("/resetPwdForm.us\",\"비밀번호 초기화\",\"width=500, height=300\");\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<header id=\"select-div\">\r\n");
      out.write("	<h3>상담</h3>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"content-div\">\r\n");
      out.write("	<div id=\"insert-div\">\r\n");
      out.write("		<table id=\"insert-table\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td rowspan=\"4\">\r\n");
      out.write("					<label for=\"studentId\">학생명 : </label>\r\n");
      out.write("					<select id=\"studentId\">\r\n");
      out.write("						");
if( sList.isEmpty() ) {
      out.write("\r\n");
      out.write("							<option value=\"\">학생 정보 없음</option>\r\n");
      out.write("						");
} else{
      out.write("\r\n");
      out.write("							");
for(Student s : sList){ 
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(s.getUserId() );
      out.write("\" > ");
      out.print(s.getUserName() );
      out.write(' ');
      out.write('(');
      out.print(s.getUserId() );
      out.write(") </option>\r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("						");
} 
      out.write("		\r\n");
      out.write("					</select>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td rowspan=\"4\">\r\n");
      out.write("					<button id=\"select-student-btn\">선택</button>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td><label for=\"consult-type\" >상담 구분</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"consult-type\" name=\"consult-category\"  disabled/></td>\r\n");
      out.write("				<td rowspan=\"4\"><label for=\"consult-content\">상담 내용</label></td>\r\n");
      out.write("				<td rowspan=\"4\"><textArea id=\"consult-content\" name=\"consultContent\" cols=\"50\" rows=\"6\" style=\"resize: none;\" disabled></textArea></td>\r\n");
      out.write("				<td style=\"display: none;\"><input type=\"hidden\" id=\"consult-csNo\"/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"consult-time\">상담 시간</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"consult-time\" name=\"consult-time\"  disabled/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"consult-date\">상담 날짜</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"consult-date\" name=\"consult-date\"  disabled/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><label for=\"consult-date\">상담 방식</label></td>\r\n");
      out.write("				<td><input type=\"text\" id=\"consult-way\" name=\"consult-way\"  disabled/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<br>\r\n");
      out.write("		<button id=\"insert-btn\" type=\"submit\">저장</button>\r\n");
      out.write("		<button id=\"update-btn\" type=\"submit\">수정</button>\r\n");
      out.write("		<button id='delete-btn' type='submit'>삭제</button>\r\n");
      out.write("		<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table id=\"consulting-table\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>순번</th>\r\n");
      out.write("				<th>상담 내용</th>\r\n");
      out.write("				<th>상담 날짜</th>\r\n");
      out.write("				<th>상담 방식</th>\r\n");
      out.write("				<th>상담 시간</th>\r\n");
      out.write("				<th>상담 구분</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody id=\"consultingListArea\">\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"footer-div\">\r\n");
      out.write("		<button id=\"area-reset-btn\">추가하기</button>\r\n");
      out.write("	<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("	</div> \r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	$(function(){\r\n");
      out.write("		let cPage;\r\n");
      out.write("		$.datepicker.setDefaults($.datepicker.regional['ko']); \r\n");
      out.write("	    $(\"#consult-date\" ).datepicker({\r\n");
      out.write("	         changeMonth: true, \r\n");
      out.write("	         changeYear: true,\r\n");
      out.write("	         nextText: '다음 달',\r\n");
      out.write("	         prevText: '이전 달', \r\n");
      out.write("	         dayNames: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],\r\n");
      out.write("	         dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'], \r\n");
      out.write("	         monthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("	         monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("	         dateFormat: \"yy-mm-dd\",\r\n");
      out.write("	         maxDate: 0,                       // 선택할수있는 최소날짜, ( 0 : 오늘 이후 날짜 선택 불가)\r\n");
      out.write("	         onClose: function( selectedDate ) {    \r\n");
      out.write("	         }    \r\n");
      out.write("\r\n");
      out.write("	    });\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("		/*동적으로 생긴 버튼은 이런식으로 on을 써줘야함*/\r\n");
      out.write("		/* consulting 테이블의 row를 클릭했을때 이벤트 발생 */\r\n");
      out.write("		$(document).on(\"click\",\".consulting-tr\",function(){\r\n");
      out.write("			\r\n");
      out.write("			$('#delete-btn').css('display','inline-block');\r\n");
      out.write("			$('#update-btn').css('display','inline-block');\r\n");
      out.write("			$('#insert-btn').css('display','none');\r\n");
      out.write("			\r\n");
      out.write("			$('#delete-btn').css('visibility','visible');\r\n");
      out.write("			$('#update-btn').css('visibility','visible');\r\n");
      out.write("			$('#insert-btn').css('visibility','hidden');\r\n");
      out.write("			\r\n");
      out.write("			const sId= $('#studentId').val();		\r\n");
      out.write("			const content =$(this).children().eq(1).text();\r\n");
      out.write("			const date = $(this).children().eq(2).text();\r\n");
      out.write("			const way = $(this).children().eq(3).text();\r\n");
      out.write("			const time = $(this).children().eq(4).text();\r\n");
      out.write("			const type = $(this).children().eq(5).text();\r\n");
      out.write("			const csNo=  $(this).children().eq(6).text();\r\n");
      out.write("			\r\n");
      out.write("			$(\"#consult-type\").val(type);\r\n");
      out.write("			$(\"#consult-content\").val(content);\r\n");
      out.write("			$(\"#consult-time\").val(time);\r\n");
      out.write("			$(\"#consult-date\").val(date);\r\n");
      out.write("			$(\"#consult-way\").val(way);\r\n");
      out.write("			$(\"#consult-csNo\").val(csNo);\r\n");
      out.write("			\r\n");
      out.write(" \r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		/* 추가하기 버튼 눌렀을 때 */\r\n");
      out.write("		$(\"#area-reset-btn\").click(function(){\r\n");
      out.write("\r\n");
      out.write("			$('#delete-btn').css('display','none');\r\n");
      out.write("			$('#update-btn').css('display','none');\r\n");
      out.write("			$('#insert-btn').css('display','inline-block');\r\n");
      out.write("			\r\n");
      out.write("			$('#delete-btn').css('visibility','hidden');\r\n");
      out.write("			$('#update-btn').css('visibility','hidden');\r\n");
      out.write("			$('#insert-btn').css('visibility','visible');\r\n");
      out.write("			\r\n");
      out.write("			emptyValue();\r\n");
      out.write("			setDisabledInput(false);\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		/* 추가 버튼 눌렀을때*/\r\n");
      out.write("		$(\"#insert-btn\").click(function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"insertConsulting.pr\",\r\n");
      out.write("				data:{\r\n");
      out.write("					sId:$(\"#studentId\").val(),\r\n");
      out.write("					type:$(\"#consult-type\").val(),\r\n");
      out.write("					content:$(\"#consult-content\").val(),\r\n");
      out.write("					time:$(\"#consult-time\").val(),\r\n");
      out.write("					date:$(\"#consult-date\").val(),\r\n");
      out.write("					way:$(\"#consult-way\").val()\r\n");
      out.write("				},\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				success:function(){\r\n");
      out.write("					selectConsultingList(cPage);\r\n");
      out.write("					alert(\"저장이 완료되었습니다.\");\r\n");
      out.write("				},\r\n");
      out.write("				error:function(){\r\n");
      out.write("					console.log(\"ajax 통신 실패\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		/* 수정하기 버튼 눌렀을 때 */\r\n");
      out.write("		$(\"#update-btn\").click(function(){\r\n");
      out.write("			if(confirm(\"수정하시겠습니까?\\n(수정하시려면 '확인', 수정하지 않으려면 '취소'를 누르십시오.) \")){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url:\"updateConsulting.pr\",\r\n");
      out.write("					data:{\r\n");
      out.write("						sId:$(\"#studentId\").val(),\r\n");
      out.write("						type:$(\"#consult-type\").val(),\r\n");
      out.write("						content:$(\"#consult-content\").val(),\r\n");
      out.write("						time:$(\"#consult-time\").val(),\r\n");
      out.write("						date:$(\"#consult-date\").val(),\r\n");
      out.write("						way:$(\"#consult-way\").val(),\r\n");
      out.write("						csNo:$(\"#consult-csNo\").val()\r\n");
      out.write("					},\r\n");
      out.write("					type:\"post\",\r\n");
      out.write("					success:function(){\r\n");
      out.write("						selectConsultingList(cPage);\r\n");
      out.write("						\r\n");
      out.write("						emptyValue();\r\n");
      out.write("						setDisabledInput(true);\r\n");
      out.write("						\r\n");
      out.write("						alert(\"수정이 완료되었습니다.\");\r\n");
      out.write("					},\r\n");
      out.write("					error:function(){\r\n");
      out.write("						console.log(\"ajax 통신 실패\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			  \r\n");
      out.write("			 }\r\n");
      out.write("			 else{\r\n");
      out.write("			 	alert('수정을 취소합니다.');\r\n");
      out.write("			 }\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		/* 삭제 버튼 눌렀을 때 */\r\n");
      out.write("		$(\"#delete-btn\").click(function(){\r\n");
      out.write("			if(confirm(\"삭제하시겠습니까?\\n(삭제하시려면 '확인', 삭제하지 않으려면 '취소'를 누르십시오.) \")){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url:\"deleteConsulting.pr\",\r\n");
      out.write("					data:{\r\n");
      out.write("						csNo:$(\"#consult-csNo\").val()\r\n");
      out.write("					},\r\n");
      out.write("					type:\"post\",\r\n");
      out.write("					success:function(){\r\n");
      out.write("						selectConsultingList(cPage);\r\n");
      out.write("						emptyValue();\r\n");
      out.write("						setDisabledInput(true);\r\n");
      out.write("						alert(\"삭제가 완료되었습니다.\");\r\n");
      out.write("					},\r\n");
      out.write("					error:function(){\r\n");
      out.write("						console.log(\"ajax 통신 실패\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			 }\r\n");
      out.write("			else{\r\n");
      out.write("				alert('삭제를 취소합니다.');\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		/* 학생 선택 후 선택 버튼 클릭 시  */\r\n");
      out.write("		$(\"#select-student-btn\").click(function(){\r\n");
      out.write("			emptyValue();\r\n");
      out.write("			setDisabledInput(false);\r\n");
      out.write("			selectConsultingList(1);\r\n");
      out.write("		})\r\n");
      out.write("	\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	function selectConsultingList(cPage){\r\n");
      out.write("		$(\"#consultingListArea\").empty();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"selectConsultingList.pr\",\r\n");
      out.write("			data:{\r\n");
      out.write("				sId:$(\"#studentId\").val(),\r\n");
      out.write("				currentPage:cPage\r\n");
      out.write("			},\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			success:function(result){\r\n");
      out.write("				console.log(result);\r\n");
      out.write("				const pi=result.pi;\r\n");
      out.write("				const list=result.sc;\r\n");
      out.write("				\r\n");
      out.write("				console.log(pi.listLimit);\r\n");
      out.write("				$.each(list, function(index, obj){\r\n");
      out.write("					const csNo= $(\"<td  class='no-td' style='visibility:hidden;display:none;position:absolute;'>\").text(obj.csNo);\r\n");
      out.write("					const idx= $(\"<td  class='index-td'>\").text(index+1+pi.boardLimit*(cPage-1));\r\n");
      out.write("					const date = $(\"<td  class='date-td'>\").text(obj.csDate);\r\n");
      out.write("					const content = $(\"<td  class='content-td'>\").text(obj.csContent);\r\n");
      out.write("					const time = $(\"<td  class='time-td'>\").text(obj.csTime);\r\n");
      out.write("					const way = $(\"<td  class='way-td'>\").text(obj.csWay);\r\n");
      out.write("					const type = $(\"<td  class='type-td'>\").text(obj.csType);\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					const tr = $(\"<tr class='consulting-tr'>\").append(idx, content, date, way , time, type,csNo);\r\n");
      out.write("					$(\"#consultingListArea\").append(tr);\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("				pagingSetting(pi);\r\n");
      out.write("			},\r\n");
      out.write("			error:function(){\r\n");
      out.write("				console.log(\"ajax 통신 실패\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function pagingSetting(pi){\r\n");
      out.write("		cPage=pi.currentPage;\r\n");
      out.write("		$(\".pagingArea\").empty();\r\n");
      out.write("\r\n");
      out.write("		//맨처음 <<\r\n");
      out.write("		let startBtn=$(\"<button onclick='selectConsultingList(1);'>\");\r\n");
      out.write("		$(\".pagingArea\").append(startBtn.text(\"<<\"));\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		//이전페이지 <\r\n");
      out.write("		if(pi.currentPage == 1){\r\n");
      out.write("			$(\".pagingArea\").append($(\"<button disabled>\").text(\"<\"));\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		else{\r\n");
      out.write("			$(\".pagingArea\").append($(\"<button onclick='selectConsultingList(\"+(cPage-1)+\");'>\").text(\"<\"));\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//페이지 목록 1,2,3,...\r\n");
      out.write("		for(let p=pi.startPage; p<=pi.endPage; p++){\r\n");
      out.write("			if(p==pi.currentPage){\r\n");
      out.write("				$(\".pagingArea\").append($(\"<button disabled>\").text(p));\r\n");
      out.write("			}\r\n");
      out.write("			else{\r\n");
      out.write("				$(\".pagingArea\").append($(\"<button onclick='selectConsultingList(\"+p+\");'>\").text(p));	\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//다음페이지로 >\r\n");
      out.write("		if(pi.currentPage == pi.maxPage){\r\n");
      out.write("			$(\".pagingArea\").append($(\"<button disabled>\").text(\">\"));\r\n");
      out.write("		}\r\n");
      out.write("		else{\r\n");
      out.write("			$(\".pagingArea\").append($(\"<button onclick='selectConsultingList(\"+(cPage+1)+\");'>\").text(\">\"));\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//맨 끝 페이지로 >>\r\n");
      out.write("		$(\".pagingArea\").append($(\"<button onclick='selectConsultingList(\"+(pi.maxPage)+\");'>\").text(\">>\"));\r\n");
      out.write("		\r\n");
      out.write("		$(\".pagingArea button\").css(\"margin\",\"4px\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function emptyValue(){\r\n");
      out.write("		$(\"#consult-type\").val(\"\");\r\n");
      out.write("		$(\"#consult-content\").val(\"\");\r\n");
      out.write("		$(\"#consult-time\").val(\"\");\r\n");
      out.write("		$(\"#consult-date\").val(\"\");\r\n");
      out.write("		$(\"#consult-way\").val(\"\");\r\n");
      out.write("		$(\"#consult-csNo\").val(\"\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function setDisabledInput(flag){\r\n");
      out.write("		$(\"#consult-type\").attr(\"disabled\", flag);\r\n");
      out.write("		$(\"#consult-content\").attr(\"disabled\", flag);\r\n");
      out.write("		$(\"#consult-time\").attr(\"disabled\", flag);\r\n");
      out.write("		$(\"#consult-date\").attr(\"disabled\", flag);\r\n");
      out.write("		$(\"#consult-way\").attr(\"disabled\", flag);\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
