/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-25 00:06:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sun.user.model.vo.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/../common/logoutIndex.jsp", Long.valueOf(1629808238000L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1629808238000L));
    _jspx_dependants.put("/views/common/index.jsp", Long.valueOf(1629849898000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sun.user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	User u = (User) session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

User loginUser = (User) session.getAttribute("loginUser");
String msg = (String) session.getAttribute("msg");
String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("<!--login이 되어있을 때의 style -->\r\n");
      out.write("\r\n");
      out.write("#top{\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" #logo { \r\n");
      out.write(" 	display:block-inline;\r\n");
      out.write("	padding-right: 80%;\r\n");
      out.write("	text-decoration-line: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-user-name, #logout {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: #00205b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu ul li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #00205b;\r\n");
      out.write("	float: left;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-left: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu .menuLink {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 125px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topMenu .menuLink:hover {\r\n");
      out.write("	color: #092d70;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo:link {text-decoration: none;}\r\n");
      out.write("#logo:visited {text-decoration: none;}\r\n");
      out.write("#logo:hover {text-decoration:  none;}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("	height: 5%;\r\n");
      out.write("}\r\n");
      out.write("nav {\r\n");
      out.write("	background-color: rgb(3, 33, 89);\r\n");
      out.write("	margin: 5px 0px;\r\n");
      out.write("}\r\n");
      out.write("nav>ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	margin-right: 300px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("nav li {\r\n");
      out.write("	float:left;\r\n");
      out.write("	width: 15%;\r\n");
      out.write("	/*margin: 10%;*/\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("/*\r\n");
      out.write("div{\r\n");
      out.write(" border: 1px solid red;\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$( function(){\r\n");
      out.write("		var msg=\"");
      out.print(msg);
      out.write("\";\r\n");
      out.write("		if (msg != \"null\") {\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
session.removeAttribute("msg");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("	function loginVaildate() {\r\n");
      out.write("		if ($(\"#userId\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$(\"#userId\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if ($(\"#userPwd\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			$(\"#userPwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		");

		if (loginUser == null) {
		
      out.write("\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("login이 안 되어있을 때의 style \r\n");
      out.write("-->\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #dae6f0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	padding-right: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#find-div>a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-container {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	background-color: #63718b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-logo, #main-img {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-div {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-left: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-btn {\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	outline: 0;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lock-div {\r\n");
      out.write("	margin-top: 120px;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-text {\r\n");
      out.write("	font-size: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lock-img {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	vertical-align: text-bottom;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#find-div {\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	function loginVaildate() {\r\n");
      out.write("		if ($(\"#userId\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			$(\"#userId\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if ($(\"#userPwd\").val().trim().length == 0) {\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			$(\"#userPwd\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div id=\"main-div\">\r\n");
      out.write("			<img id=\"main-logo\" src=\"resources/images/sunLogo1.png\" alt=\"\"\r\n");
      out.write("				width=\"200px\"> <img id=\"main-img\"\r\n");
      out.write("				src=\"resources/images/sunUni.jpg\" alt=\"\" width=\"500px\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"main-container\">\r\n");
      out.write("			<div id=\"lock-div\">\r\n");
      out.write("				<img id=\"lock-img\" src=\"resources/images/lock.png\" alt=\"\"\r\n");
      out.write("					width=\"100px\"> <span id=\"login-text\">LOGIN</span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/login\"\r\n");
      out.write("				method=\"post\" onsubmit=\"return loginVaildate();\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><label for=\"userId\">아이디</label></th>\r\n");
      out.write("						<td><input type=\"text\" id=\"userId\" name=\"userId\"></td>\r\n");
      out.write("\r\n");
      out.write("						<td rowspan=\"2\"><button type=\"submit\" id=\"login-btn\">LOGIN</button></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th><label for=\"userPwd\">비밀번호</label></th>\r\n");
      out.write("						<td><input type=\"password\" id=\"userPwd\" name=\"userPwd\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"find-div\">\r\n");
      out.write("				<a onclick=\"findId();\">>학번/교직원 번호 찾기</a> <a onclick=\"resetPwd();\">>비밀번호\r\n");
      out.write("					초기화 </a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<div id=\"top\" style=\"background-color:white;\">\r\n");
      out.write("			<a id='logo' href=\"");
      out.print(contextPath);
      out.write("\"> <img src=\"resources/images/sunLogo1.png\" width=\"140px\" height=\"70px\"></a> \r\n");
      out.write("			<span id=\"login-user-name\"> ");
      out.print(loginUser.getUserName() );
      out.write("님\r\n");
      out.write("			<a href = \"");
      out.print(contextPath);
      out.write("/logout\">로그아웃</a></span>\r\n");
      out.write("		\r\n");
      out.write("	<nav id=\"topMenu\">\r\n");
      out.write("	");

	if (Character.toUpperCase(loginUser.getUserId().charAt(0)) == 'A') { //관리자
	
      out.write("\r\n");
      out.write("	<div align=\"right\" >\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goStudentManagement();\">학생 관리</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goManageProfessors();\">교수 관리</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goManageClass();\">강의 관리</div></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	} else if (Character.toUpperCase(loginUser.getUserId().charAt(0)) == 'P') { //교수
	
      out.write("\r\n");
      out.write("	<div align=\"right\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goProfessorsClass();\">강의</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goProfessorsGrade();\">성적</div></li>\r\n");
      out.write("		<li><div class=\"menuLink\" onclick=\"goProfessorsConsulting();\">상담</div></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	} else { // 학생
	
      out.write("\r\n");
      out.write("	<div align=\"left\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goStudentRegister();\">학적</div></li>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goStudentConsulting();\">상담</div></li>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goStudentGrade();\">성적</div></li>\r\n");
      out.write("		<li><div id = \"4\" class=\"menuLink\" onclick=\"goCertification('https://www.webminwon.com/#reload');\">증명서발급</div></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
}}
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("    \r\n");
      out.write("   function goStudentManagement(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/list.st\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goProfessorsClass(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/classList.pr\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function goProfessorsGrade(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/gradeList.pr\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goProfessorsConsulting(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/consultingList.pr\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goStudentRegister(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/StudentAcademic\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goStudentConsulting(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/student.consult\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goStudentGrade(){\r\n");
      out.write("		location.href=\"");
      out.print(request.getContextPath());
      out.write("/student.grade\";\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function goCertification(url) {\r\n");
      out.write("        var win = window.open(url, '_blank');\r\n");
      out.write("        win.focus();\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	function findId(){\r\n");
      out.write("		window.open(\"");
      out.print(contextPath);
      out.write("/findIdForm.us\",\"아이디 찾기\",\"width=500, height=300\");\r\n");
      out.write("	}\r\n");
      out.write("	function resetPwd(){\r\n");
      out.write("		window.open(\"");
      out.print(contextPath);
      out.write("/resetPwdForm.us\",\"비밀번호 초기화\",\"width=500, height=300\");\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(u!=null){
      out.write("	\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/92a9092640.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	body{\r\n");
      out.write("		background-image:url('resources/images/sunUniBackground.png');\r\n");
      out.write("		background-repeat:no-repat;\r\n");
      out.write("		background-size:cover;\r\n");
      out.write("	}\r\n");
      out.write("	.outer{\r\n");
      out.write("		width: 1200px;\r\n");
      out.write("		margin-right:20%;\r\n");
      out.write("		/*display: inline-block;\r\n");
      out.write("		width:1200px;\r\n");
      out.write("		height:900px;	*/\r\n");
      out.write("	}\r\n");
      out.write("	/*\r\n");
      out.write("	.outer>*{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	}*/\r\n");
      out.write("	#map{\r\n");
      out.write("		margin-top: 80px;\r\n");
      out.write("		margin-right: 100px;\r\n");
      out.write("		margin-left:200px;\r\n");
      out.write("		float: left;\r\n");
      out.write("		border: 2px solid gray;\r\n");
      out.write("	}\r\n");
      out.write("	.weather{\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height:220px;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		margin-top: 100px;\r\n");
      out.write("		background-color: skyblue;\r\n");
      out.write("		border-radius: 2em;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	.icon{\r\n");
      out.write("		margin-top:10px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.content{\r\n");
      out.write("		height:50px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		color:white;\r\n");
      out.write("		font-weight:900;\r\n");
      out.write("		font-size:20px;\r\n");
      out.write("	}\r\n");
      out.write("	.wayToCome{\r\n");
      out.write("		border: 2px solid gray;	\r\n");
      out.write("		margin-left:200px;\r\n");
      out.write("		width:600px;\r\n");
      out.write("		height:280px;\r\n");
      out.write("		float: left;\r\n");
      out.write("		background-color: #f0f8ff;\r\n");
      out.write("	}\r\n");
      out.write("	.cal{\r\n");
      out.write("		width:300px;\r\n");
      out.write("		height:340px;\r\n");
      out.write("		margin-top:80px;\r\n");
      out.write("		font-size:25px;\r\n");
      out.write("		background-color:white;\r\n");
      out.write("		border-radius: 2em;\r\n");
      out.write("	}\r\n");
      out.write("	.bor{display:inline-block;}\r\n");
      out.write("	.empty{float:left;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"outer\">\r\n");
      out.write("		<div class=\"division\"> \r\n");
      out.write("			<div id=\"map\" style=\"width:600px;height:500px;\"></div>\r\n");
      out.write("			<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=c019dd9a3a4c3ef858ee36d226914efc\"></script>\r\n");
      out.write("			<script>\r\n");
      out.write("				var mapContainer = document.getElementById('map'),\r\n");
      out.write("				    mapOption = { \r\n");
      out.write("				        center: new kakao.maps.LatLng(37.5064613, 127.0320657),\r\n");
      out.write("				        level: 5 \r\n");
      out.write("				    };\r\n");
      out.write("				\r\n");
      out.write("				var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("				 \r\n");
      out.write("				var points = [\r\n");
      out.write("				    new kakao.maps.LatLng(37.5064613, 127.0320657),\r\n");
      out.write("				];\r\n");
      out.write("				\r\n");
      out.write("				var bounds = new kakao.maps.LatLngBounds();    \r\n");
      out.write("				\r\n");
      out.write("				var i, marker;\r\n");
      out.write("				for (i = 0; i < points.length; i++) {\r\n");
      out.write("				    marker =     new kakao.maps.Marker({ position : points[i] });\r\n");
      out.write("				    marker.setMap(map);\r\n");
      out.write("				    \r\n");
      out.write("				    bounds.extend(points[i]);\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				function setBounds() {\r\n");
      out.write("				    map.setBounds(bounds);\r\n");
      out.write("				}\r\n");
      out.write("			</script>\r\n");
      out.write("			<div class=\"wayToCome\">\r\n");
      out.write("				<br>\r\n");
      out.write("				<h5 style=\"text-decoration: underline overline 2px; text-underline-position: under; text-decoration-color: navy; color: navy;\">\r\n");
      out.write("				&nbsp;&nbsp; <strong>찾아오시는 길</strong>&nbsp;&nbsp;</h5>\r\n");
      out.write("				&nbsp;&nbsp;> 주소 : 서울특별시 강남구 테헤란로 14길 6 남도빌딩 <br>\r\n");
      out.write("				&nbsp;&nbsp;> Tel: 1544-9970 / Fax: 02-562-2378<br><br>\r\n");
      out.write("				<br>\r\n");
      out.write("				\r\n");
      out.write("				<h5 style=\"text-decoration: underline overline 2px; text-underline-position: under; text-decoration-color: navy; color: navy;\">\r\n");
      out.write("				&nbsp;&nbsp; <strong>교통편 안내</strong>&nbsp;&nbsp;</h5>\r\n");
      out.write("				&nbsp;&nbsp;> <strong>[지하철 : 2호선 역삼역 3번출구 이용]</strong><br>\r\n");
      out.write("				&nbsp;&nbsp;도보 100m<br>\r\n");
      out.write("				&nbsp;&nbsp;> <strong>[버스 : 역삼역.포스코P & S타워 정류장]</strong><br>\r\n");
      out.write("				&nbsp;&nbsp;146 / 740 / 341 / 360 / 1100 / 1700 / 2000 / 7007 / 8001<br><br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("		<div class=\"division\">\r\n");
      out.write("			<div class=\"weather\">\r\n");
      out.write("				<div class=\"icon\" ></div><!-- <img alt=\"\" src=\"http://openweathermap.org/img/wn/10d@2x.png\"> -->\r\n");
      out.write("				<div class=\"content\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<script>\r\n");
      out.write("			$.getJSON('http://api.openweathermap.org/data/2.5/weather?q=Seoul&APPID=f46d2b55a8b012ccb8136dfcce652893&units=metric' ,function(result){\r\n");
      out.write("			//result.weather[0].icon\r\n");
      out.write("			var wIconUrl = '<img alt=\"'+result.weather[0].description+'\" src=\"http://openweathermap.org/img/wn/'+result.weather[0].icon+'@2x.png\">'\r\n");
      out.write("			$('.icon').html(wIconUrl);\r\n");
      out.write("			var ct = result.dt;\r\n");
      out.write("			function convertTime(t){\r\n");
      out.write("				var ot = new Date(t*1000);\r\n");
      out.write("				\r\n");
      out.write("				return ot.toLocaleString();\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			var currentTime = convertTime(ct);\r\n");
      out.write("			$('.content').append(result.sys.country+', '+result.name+' '+result.weather[0].description+'<br>'+currentTime+'<br>'+result.main.temp+' º');\r\n");
      out.write("			});\r\n");
      out.write("		</script>\r\n");
      out.write("		<div class=\"bor\">\r\n");
      out.write("		<div class=\"empty\"></div>\r\n");
      out.write("			<div class=\"cal\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<script type=\"text/javascript\">\r\n");
      out.write("		        var today = new Date();\r\n");
      out.write("		        var date = new Date();\r\n");
      out.write("		        \r\n");
      out.write("		        function prevCalendar() {\r\n");
      out.write("		         today = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());\r\n");
      out.write("		         buildCalendar();\r\n");
      out.write("		        }\r\n");
      out.write("		 \r\n");
      out.write("		        function nextCalendar() {\r\n");
      out.write("		             today = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());\r\n");
      out.write("		             buildCalendar();\r\n");
      out.write("		        }\r\n");
      out.write("		        function buildCalendar(){\r\n");
      out.write("		            var doMonth = new Date(today.getFullYear(),today.getMonth(),1);\r\n");
      out.write("		            \r\n");
      out.write("		            var lastDate = new Date(today.getFullYear(),today.getMonth()+1,0);\r\n");
      out.write("		           \r\n");
      out.write("		            var tbCalendar = document.getElementById(\"calendar\");\r\n");
      out.write("		            var tbCalendarYM = document.getElementById(\"tbCalendarYM\");\r\n");
      out.write("		           \r\n");
      out.write("		            tbCalendarYM.innerHTML = today.getFullYear() + \"년 \" + (today.getMonth() + 1) + \"월\"; \r\n");
      out.write("		 \r\n");
      out.write("		            while (tbCalendar.rows.length > 2) {\r\n");
      out.write("		                  tbCalendar.deleteRow(tbCalendar.rows.length-1);\r\n");
      out.write("		             }\r\n");
      out.write("		             var row = null;\r\n");
      out.write("		             row = tbCalendar.insertRow();\r\n");
      out.write("		\r\n");
      out.write("		             var cnt = 0;\r\n");
      out.write("		\r\n");
      out.write("		             for (i=0; i<doMonth.getDay(); i++) {\r\n");
      out.write("		                  cell = row.insertCell();\r\n");
      out.write("		                  cnt = cnt + 1;\r\n");
      out.write("		             }\r\n");
      out.write("		\r\n");
      out.write("		             for (i=1; i<=lastDate.getDate(); i++) { \r\n");
      out.write("		                  cell = row.insertCell();\r\n");
      out.write("		                  cell.innerHTML = i;\r\n");
      out.write("		                  cnt = cnt + 1;\r\n");
      out.write("		              if (cnt % 7 == 1) {\r\n");
      out.write("		                cell.innerHTML = \"<font color=red>\" + i\r\n");
      out.write("		            }    \r\n");
      out.write("		              if (cnt%7 == 0){\r\n");
      out.write("		                  cell.innerHTML = \"<font color=red>\" + i\r\n");
      out.write("		                   row = calendar.insertRow();\r\n");
      out.write("		              }\r\n");
      out.write("		              if (today.getFullYear() == date.getFullYear()\r\n");
      out.write("		                 && today.getMonth() == date.getMonth()\r\n");
      out.write("		                 && i == date.getDate()) {\r\n");
      out.write("		                cell.bgColor = \"#FAF58C\";\r\n");
      out.write("		               }\r\n");
      out.write("		             }\r\n");
      out.write("		        }\r\n");
      out.write("		    </script>\r\n");
      out.write("	   	 	<p></p>\r\n");
      out.write("			<table id=\"calendar\" align=\"center\">\r\n");
      out.write("			    <tr>\r\n");
      out.write("			        <td><label onclick=\"prevCalendar()\"><</label></td>\r\n");
      out.write("			        <td align=\"center\" id=\"tbCalendarYM\" colspan=\"5\">yyyy년 m월</td>\r\n");
      out.write("			        <td><label onclick=\"nextCalendar()\">></label></td>\r\n");
      out.write("			    </tr>\r\n");
      out.write("			    <tr>\r\n");
      out.write("			        <td align=\"center\"><font color =\"red\">일</td>\r\n");
      out.write("			        <td align=\"center\">월</td>\r\n");
      out.write("			        <td align=\"center\">화</td>\r\n");
      out.write("			        <td align=\"center\">수</td>\r\n");
      out.write("			        <td align=\"center\">목</td>\r\n");
      out.write("			        <td align=\"center\">금</td>\r\n");
      out.write("			        <td align=\"center\"><font color =\"red\">토</td>\r\n");
      out.write("			    </tr> \r\n");
      out.write("			</table>\r\n");
      out.write("			<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("		   	 	buildCalendar();\r\n");
      out.write("			</script>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write(" 	</div>\r\n");
      out.write(" 	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
