--교수 리스트 뷰
--DROP VIEW VIEW_PROF_INFO;

CREATE OR REPLACE VIEW VIEW_PROF_INFO AS
SELECT
    P_ID,
    P_NAME,
    PROFESSORS.C_NO,
    C_NAME,
    P_PHONE,
    P_EMAIL
FROM PROFESSORS
JOIN CATEGORY ON CATEGORY.C_NO=PROFESSORS.C_NO;

COMMIT;