
--학생학적조회 뷰 VIEW_ST_ACATEMIC 수정됐습니다.
CREATE OR REPLACE VIEW VIEW_ST_ACATEMIC AS
SELECT S.S_ID "ID", 
       S.S_NAME "NAME", 
       D.DEPT_NAME "DEPT", 
       C.C_NAME "CATEGORY", 
       S.S_LEVEL "GRADE",
       P.P_NAME "PROFESSOR", 
       S.S_EDATE "EDATE",
       SUM(E.CREDIT) "SUMCREDIT",
       F.EMAIL "EMAIL", 
       F.PHONE "PHONE", 
       S.FL_CHANGE "FLUCTUATION"
FROM STUDENT S
LEFT JOIN CATEGORY C ON S.C_NO=C.C_NO
LEFT JOIN DEPARTMENT D ON C.DEPT_NO=D.DEPT_NO
LEFT JOIN PROFESSORS P ON S.P_ID=P.P_ID
LEFT JOIN VIEW_ST_EARN E ON S.S_ID=E.S_ID
LEFT JOIN ST_PERSONAL F ON S.S_ID=F.S_ID
GROUP BY S.S_ID, S.S_NAME, D.DEPT_NAME, C.C_NAME, S.S_LEVEL, P.P_NAME, S.S_EDATE, F.EMAIL, F.PHONE, S.FL_CHANGE;

--DROP VIEW VIEW_ST_ACATEMIC;

--학생신상정보 테이블 ST_PERSONAL
CREATE TABLE ST_PERSONAL (
   S_ID VARCHAR2(20) PRIMARY KEY,
   PHONE VARCHAR2(20),
   EMAIL VARCHAR2(30),
   MILITARY VARCHAR2(20),
   ADDRESS VARCHAR2(20),
   ACCOUNT VARCHAR2(20),
   BANK VARCHAR2(20),
   HOLDER VARCHAR2(20)
);

--DROP TABLE ST_PERSONAL;

CREATE OR REPLACE VIEW VIEW_CH AS
SELECT A.CLASS_YEAR,
        A.CLASS_SEMESTER,
        A.CLASS_NAME,
        A.CREDIT,
        B.CLASS_TYPE_NAME,
        C.P_NAME,
        D.S_ID
FROM CLASS A
JOIN CLASS_TYPE B ON A.CLASS_TYPE_NO = B.CLASS_TYPE_NO
JOIN PROFESSORS C ON A.P_ID=C.P_ID
JOIN STUDENT D ON C.P_ID=D.P_ID;

