--DROP문
--DROP SEQUENCE SEQ_CERTIFICATE;
--DROP SEQUENCE SEQ_CONSULTING;
--DROP SEQUENCE SEQ_FLUCTUATION;

CREATE SEQUENCE SEQ_CERTIFICATE -- 자격증
INCREMENT BY 1
START WITH 1
CACHE 20;


CREATE SEQUENCE SEQ_CONSULTING -- 상담
INCREMENT BY 1
START WITH 1
CACHE 20;


CREATE SEQUENCE SEQ_FLUCTUATION -- 학적변동
INCREMENT BY 1
START WITH 1
CACHE 20;


CREATE SEQUENCE SEQ_C101
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C102
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C101
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C102
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C103
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C104
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C105
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C106
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C107
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C108
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C201
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C202
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C203
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C204
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C205
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C206
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C207
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C301
INCREMENT BY 1
START WITH 1
CACHE 20;


CREATE SEQUENCE SEQ_C302
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C303
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C304
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C305
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C401
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C501
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C502
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C503
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C504
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C505
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C506
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C507
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C508
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C509
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C510
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C511
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C601
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C602
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C603
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C604
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C605
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C606
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C607
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C608
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C701
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C702
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C703
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C704
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C705
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C706
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C801
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C802
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C803
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C901
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C902
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C903
INCREMENT BY 1
START WITH 1
CACHE 20;

CREATE SEQUENCE SEQ_C904
INCREMENT BY 1
START WITH 1
CACHE 20;

--SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_C101';

COMMIT;
