
--관리자-학생-조회 뷰 ST_INFO
CREATE OR REPLACE VIEW VIEW_ST_INFO AS
SELECT A.S_ID,
                A.S_NAME,
                A.S_LEVEL,
                B.DEPT_NAME,
                C.C_NAME,
                D.P_NAME
FROM STUDENT A
JOIN CATEGORY C ON A.C_NO=C.C_NO
JOIN DEPARTMENT B ON C.DEPT_NO=B.DEPT_NO
JOIN PROFESSORS D ON A.P_ID = D.P_ID;

DROP VIEW VIEW_ST_GRADE;


CREATE OR REPLACE VIEW VIEW_ST_GRADE AS
SELECT H.S_ID "S_ID", C.CLASS_TYPE_NO AS "TYPENO", SUM(C.CREDIT) "CREDIT"
FROM CLASS C
JOIN CLASS_HISTORY H ON C.CLASS_NO = H.CLASS_NO
GROUP BY C.CLASS_TYPE_NO, H.S_ID;

SELECT * FROM VIEW_ST_GRADE WHERE S_ID='2021602001';
WHERE S_ID='2021602001';

--관리자-강의-조회 뷰
CREATE OR REPLACE VIEW VIEW_CLASS_INFO AS
SELECT *
FROM CLASS;