

-- 학부 INSERT문
INSERT INTO DEPARTMENT VALUES ('D100','인문대학');
INSERT INTO DEPARTMENT VALUES ('D200','사회과학대학');
INSERT INTO DEPARTMENT VALUES ('D300','자연과학대학');
INSERT INTO DEPARTMENT VALUES ('D400','경영대학');
INSERT INTO DEPARTMENT VALUES ('D500','공과대학');
INSERT INTO DEPARTMENT VALUES ('D600','농업생명과학대학');
INSERT INTO DEPARTMENT VALUES ('D700','음악대학');
INSERT INTO DEPARTMENT VALUES ('D800','생활과학대학');
INSERT INTO DEPARTMENT VALUES ('D900','의과대학');
