
--학생성적조회 뷰 VIEW_ST_GRADE
CREATE OR REPLACE VIEW VIEW_ST_GRADE AS
SELECT H.S_ID "S_ID", C.CLASS_TYPE_NO AS "TYPENO", SUM(C.CREDIT) "CREDIT"
FROM CLASS C
JOIN CLASS_HISTORY H ON C.CLASS_NO = H.CLASS_NO
GROUP BY C.CLASS_TYPE_NO, H.S_ID;

--DROP VIEW VIEW_ST_GRADE;


--학생신청학점조회 뷰 VIEW_ST_APPLI
CREATE OR REPLACE VIEW VIEW_ST_APPLI AS
SELECT H.S_ID "S_ID",
       C.CLASS_YEAR "YEAR", 
       C.CLASS_SEMESTER "SEMESTER", 
       SUM(C.CREDIT) "CREDIT",  
       AVG(H.CG_POINT) "CG_POINT", 
       (AVG(H.CG_POINT)-2)*12+70 "PERCENT"
FROM CLASS_HISTORY H
JOIN CLASS C ON H.CLASS_NO = C.CLASS_NO
GROUP BY C.CLASS_YEAR, C.CLASS_SEMESTER, H.S_ID
ORDER BY 1,2;

--DROP VIEW VIEW_ST_APPLI;


--학생취득학점조회 뷰 VIEW_ST_EARN
CREATE OR REPLACE VIEW VIEW_ST_EARN AS
SELECT SUM(C.CREDIT) "CREDIT", H.S_ID "S_ID"
FROM CLASS C 
JOIN CLASS_HISTORY H ON C.CLASS_NO=H.CLASS_NO 
WHERE H.CG_POINT IS NOT NULL 
GROUP BY C.CLASS_YEAR,C.CLASS_SEMESTER, H.S_ID
ORDER BY C.CLASS_YEAR, C.CLASS_SEMESTER;

--DROP VIEW VIEW_ST_EARN;


--학생전공석차조회 뷰 VIEW_ST_RANK
CREATE OR REPLACE VIEW VIEW_ST_RANK AS
SELECT H.S_ID "S_ID",
       S.C_NO "C_NO", 
       C.CLASS_YEAR "YEAR", 
       C.CLASS_SEMESTER "SEMESTER", 
       AVG(H.CG_POINT) "AVG", 
       DENSE_RANK()OVER(PARTITION BY S.C_NO, C.CLASS_YEAR, C.CLASS_SEMESTER ORDER BY AVG(H.CG_POINT)) "RANK"
FROM CLASS_HISTORY H 
JOIN STUDENT S ON H.S_ID=S.S_ID
JOIN CLASS C ON C.CLASS_NO = H.CLASS_NO
GROUP BY S.C_NO, C.CLASS_YEAR, C.CLASS_SEMESTER, H.S_ID
ORDER BY S.C_NO, C.CLASS_YEAR, C.CLASS_SEMESTER;

--DROP VIEW VIEW_ST_RANK;
