-- 학부 INSERT문
--DELETE FROM DEPARTMENT ;

INSERT INTO DEPARTMENT VALUES ('D100','인문대학');
INSERT INTO DEPARTMENT VALUES ('D200','사회과학대학');
INSERT INTO DEPARTMENT VALUES ('D300','자연과학대학');
INSERT INTO DEPARTMENT VALUES ('D400','경영대학');
INSERT INTO DEPARTMENT VALUES ('D500','공과대학');
INSERT INTO DEPARTMENT VALUES ('D600','농업생명과학대학');
INSERT INTO DEPARTMENT VALUES ('D700','음악대학');
INSERT INTO DEPARTMENT VALUES ('D800','생활과학대학');
INSERT INTO DEPARTMENT VALUES ('D900','의과대학');

-- 학과 INSERT문
--DELETE FROM CATEGORY;

INSERT INTO CATEGORY VALUES('C101','국어국문학과','D100');
INSERT INTO CATEGORY VALUES('C102','중어중문학과','D100');
INSERT INTO CATEGORY VALUES('C103','영어영문학과','D100');
INSERT INTO CATEGORY VALUES('C104','불어불문학과','D100');
INSERT INTO CATEGORY VALUES('C105','국사학과','D100');
INSERT INTO CATEGORY VALUES('C106','동양사학과','D100');
INSERT INTO CATEGORY VALUES('C107','서양사학과','D100');
INSERT INTO CATEGORY VALUES('C108','철학과','D100');

INSERT INTO CATEGORY VALUES('C201','정치외교학과','D200');
INSERT INTO CATEGORY VALUES('C202','사회학과','D200');
INSERT INTO CATEGORY VALUES('C203','인류학과','D200');
INSERT INTO CATEGORY VALUES('C204','심리학과','D200');
INSERT INTO CATEGORY VALUES('C205','지리학과','D200');
INSERT INTO CATEGORY VALUES('C206','사회복지학과','D200');
INSERT INTO CATEGORY VALUES('C207','언론정보학과','D200');

INSERT INTO CATEGORY VALUES('C301','수리과학과','D300');
INSERT INTO CATEGORY VALUES('C302','통계학과','D300');
INSERT INTO CATEGORY VALUES('C303','화학과','D300');
INSERT INTO CATEGORY VALUES('C304','물리학과','D300');
INSERT INTO CATEGORY VALUES('C305','생명과학과','D300');

INSERT INTO CATEGORY VALUES('C401','경영학과','D400');

INSERT INTO CATEGORY VALUES('C501','기계공학과','D500');
INSERT INTO CATEGORY VALUES('C502','항공우주공학과','D500');
INSERT INTO CATEGORY VALUES('C503','전자전기공학과','D500');
INSERT INTO CATEGORY VALUES('C504','컴퓨터공학과','D500');
INSERT INTO CATEGORY VALUES('C505','오징어심리학과','D500');
INSERT INTO CATEGORY VALUES('C506','건축학과','D500');
INSERT INTO CATEGORY VALUES('C507','산업공학과','D500');
INSERT INTO CATEGORY VALUES('C508','원자핵공학과','D500');
INSERT INTO CATEGORY VALUES('C509','조선해양공학과','D500');
INSERT INTO CATEGORY VALUES('C510','에너지자원공학과','D500');
INSERT INTO CATEGORY VALUES('C511','임베디드시스템공학과','D500');

INSERT INTO CATEGORY VALUES('C601','식물생산과학과','D600');
INSERT INTO CATEGORY VALUES('C602','산림과학과','D600');
INSERT INTO CATEGORY VALUES('C603','응용생물화학부','D600');
INSERT INTO CATEGORY VALUES('C604','감귤포장학과','D600');
INSERT INTO CATEGORY VALUES('C605','독버섯심리학과','D600');
INSERT INTO CATEGORY VALUES('C606','바이오시스템학과','D600');
INSERT INTO CATEGORY VALUES('C607','농경제사회학과','D600');
INSERT INTO CATEGORY VALUES('C608','조경학과','D600');

INSERT INTO CATEGORY VALUES('C701','성악과','D700');
INSERT INTO CATEGORY VALUES('C702','작곡과','D700');
INSERT INTO CATEGORY VALUES('C703','기악과','D700');
INSERT INTO CATEGORY VALUES('C704','민요학과','D700');
INSERT INTO CATEGORY VALUES('C705','국악과','D700');
INSERT INTO CATEGORY VALUES('C706','휘파람학과','D700');

INSERT INTO CATEGORY VALUES('C801','소비자아동학과','D800');
INSERT INTO CATEGORY VALUES('C802','식품영양학과','D800');
INSERT INTO CATEGORY VALUES('C803','의류학과','D800');

INSERT INTO CATEGORY VALUES('C901','의예과','D900');
INSERT INTO CATEGORY VALUES('C902','수의학과','D900');
INSERT INTO CATEGORY VALUES('C903','약학과','D900');
INSERT INTO CATEGORY VALUES('C904','오장육부학과','D900');



--강의 타입
--DELETE FROM CLASS_TYPE ;

INSERT INTO CLASS_TYPE VALUES(1,'전공필수');
INSERT INTO CLASS_TYPE VALUES(2,'전공선택');
INSERT INTO CLASS_TYPE VALUES(3,'교양필수');
INSERT INTO CLASS_TYPE VALUES(4,'교양선택');
INSERT INTO CLASS_TYPE VALUES(5,'산학');
INSERT INTO CLASS_TYPE VALUES(6,'자유');


INSERT INTO ADMIN VALUES('A00001','admin','관리자');

COMMIT;

